### ISSUE TITLE
generate data

### ISSUE THREAD

**Issue by JianfeiZhou19** [ZhengyuLiang24/BasicLFSR#2]
why don't use python generate train and test data?

**Comment by JianfeiZhou19** [comment]
@YingqianWang @ZhengyuLiang24

**Comment by ZhengyuLiang24** [comment]
We have added the dataset generation code based on Python, i.e., 'Generate_Data_for_Training.py' and 'Generate_Data_for_Test.py'. Please check.

**Comment by JianfeiZhou19** [comment]
ok, thanks.
