### ISSUE TITLE
train/test data

### ISSUE THREAD

**Issue by JianfeiZhou19** [ZhengyuLiang24/BasicLFSR#3]
the model LF-InterNet use macro-pixel image as input for train and test, but in this repo generate SAI image?

**Comment by ZhengyuLiang24** [comment]
LF_InterNet.py in this repo includes an additional operation, i.e., x = SAI2MacPI(x, self.angRes), which can covert the SAI images to macro-pixel images for LF-InterNet.

**Comment by JianfeiZhou19** [comment]
ok, thanks.
