### ISSUE TITLE
Sharing pre-trained weights

### ISSUE THREAD

**Issue by dcazzato** [ZhengyuLiang24/BasicLFSR#5]
Is there any plan to share the pre-trained pth for such models?

**Comment by ZhengyuLiang24** [comment]
We have uploaded our pre-trained models, please refer to [this link](https://stuxidianeducn-my.sharepoint.com/:f:/g/personal/zyliang_stu_xidian_edu_cn/EtUBJ4eHG7BCjnUmtXpu9o0BvGVk5_v-RG95R_aRN46UwQ).

**Comment by dcazzato** [comment]
Amazing, thank you so much!
